# This workflow will build a .NET project
#Example for building multiple 
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Matrix Build Test

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ${{ matrix.os }}
    # continue other jobs when one job failed
    continue-on-error: true

    # creating a matrix to run multiple jobs for different os with different version of dotnet
    strategy:
      matrix:
          os: [ windows-latest, ubuntu-latest ]
          dot-net-version: [ 8.0.x ]
          
      
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
